# Generated by Django 3.1.2 on 2020-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.IntegerField()),
                ('blog_slug', models.CharField(max_length=50)),
                ('blog_content', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('author_uid', models.IntegerField()),
            ],
            options={
                'db_table': 'blog_post',
                'ordering': ['-created_date'],
            },
        ),
    ]
