# Generated by Django 3.1.2 on 2020-10-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justdotolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='uid',
            new_name='id',
        ),
    ]
